<?php

namespace app\models;

use app\models\Authors;
use Yii;
use yii\web\UploadedFile;
use app\models\ImageUpload;

/**
 * This is the model class for table "book".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $image
 * @property string|null $description
 * @property int $author_id
 * @property string|null $date
 *
 * @property Authors[] $authors
 */
class Booklist extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'book';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['author_id'], 'required'],
            [['author_id'], 'integer'],
            [['date'], 'safe'],
            [['name', 'image'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'image' => 'Image',
            'description' => 'Описание',
            'author_id' => 'Автор',
            'date' => 'Дата публикации',
            'fullName'=>'Author(Геттер)'
        ];
    }
    /**
     * {@SetImage}
     */
    public function actionSetImage($id)
    {

        $model= new ImageUpload;


        if (Yii::$app->request->isPost){
            $book=$this->findModel($id);

            $file=UploadedFile::getInstance($model,'image');

            $book->saveImage($model->upload($file,$book->image));

            $this->redirect(['view', 'id' => $book->id]);


        }

        return $this->renderAjax('image',['model'=>$model]);
    }

    /**
     * Gets query for [[Authors]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAuthors()
    {
        return $this->hasOne(Authors::className(), ['id' => 'author_id']);
    }

    public function getPosts()
    {
        return $this->hasMany(Authors::className(), ['id' => 'book_id'])
            ->viaTable('posts', ['author_id' => 'id']);
    }

        /**
     * Gets query for [[fullName of Authors]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getFullName(){
        return $this->authors->FullName;

    }
    /**
     * Gets query for [[Image]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function saveImage($filename)
    {
        $this->image= $filename;
        $this->save(false);
    }

    public function deleteImage()
    {
        $ImageUploadModel = new ImageUpload();
        $ImageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub

    }
    public function getImage()
    {

        return ($this->image) ? 'uploads/'. $this->image : 'no-image.jpg';

    }
}
